"""add group photo to teams

Revision ID: 69a27181a99a
Revises: 0fae9f53f0a3
Create Date: 2026-09-17 21:23:31.887941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a27181a99a'
down_revision: Union[str, Sequence[str], None] = '0fae9f53f0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('group_photo_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'group_photo_path')
    # ### end Alembic commands ###
