"""add event settings table

Revision ID: d658a263fea5
Revises: 9de3829a9517
Create Date: 2026-09-20 01:55:01.822045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd658a263fea5'
down_revision: Union[str, Sequence[str], None] = '9de3829a9517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('problem_release_status', sa.String(length=30), server_default='not_started', nullable=False),
    sa.Column('problem_release_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('repository_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('feedback_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute(
        "INSERT INTO event_settings (id, problem_release_status, repository_active, feedback_active) "
        "VALUES (1, 'not_started', false, false) ON CONFLICT (id) DO NOTHING"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_settings')
    # ### end Alembic commands ###
